### PR TITLE
Update Snakefile

### PR DESCRIPTION
**Pull request by DimaMolod**
create_features produces either *.pkl or *.pkl.xz files. Removed conda from all rules.

### CODE REVIEW

**Comment by DimaMolod** [comment]
@maurerv AP can now generate compressed features and read from them while folding. I tried to accommodate these changes in Snakemake and removed Conda to see if it removed the error message.

**Comment by maurerv** [comment]
Hi @DimaMolod,

What is the state of this pull request?

Do your changes work, or is this an initial implementation you would like feedback on? From what I see, snakemake now expects create_features always to produce two files, one ending in pkl and one in pkl.xz. The pkl.xz files, however, are never passed to any downstream rules like structure_inference.

**Comment by DimaMolod** [comment]
Hi @maurerv,
no, this PR is just a way to show it to you and get some feedback.
Yes, you are right about the downstream rules, thanks. I'll try to fix that...

**Comment by maurerv** [comment]
Okay, thanks for clarifying.

Does the pickle file reader/writer in AP depend on the file extension to handle features correctly?

**Comment by DimaMolod** [comment]
> Okay, thanks for clarifying.
> 
> Does the pickle file reader/writer in AP depend on the file extension to handle features correctly?

Yes, exactly. It check for the extension here:
https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/utils/modelling_setup.py#L262-L270

**Comment by DimaMolod** [comment]
the writer (create_individual_features.py) depends on the new flag --compress-features, which is set to False (don't write) by default

**Comment by maurerv** [comment]
Okay, otherwise we could have just ignored the extension ;) 

I think there is no particularly clean way of implementing this feature, because the on-the-fly sequence clustering has made the workflow fairly complicated. Perhaps the easiest way is to add a _format_feature_extension function that adds the correct extension

**Comment by DimaMolod** [comment]
Well, the other option would be to change it on AP side e.g. always try to uncompress the feature before processing further, but this also doesn't seem like a clean solution :-)

**Comment by maurerv** [comment]
Indeed :) Either way is fine with me tbh. I think since the pickle files are specific to AP anyways, we could justify handling the compression/decompression in AP. This would most likely require less code than adding it to snakemake and perhaps also be more convenient for AP users

**Comment by DimaMolod** [comment]
ok, then let us proceed with the _format_feature_extension function, as you suggested.

**Pull request closed without merging**
